2025-02-21 17:18:36,617 INFO    StreamThr :23009 [internal.py:wandb_internal():85] W&B internal server running at pid: 23009, started at: 2025-02-21 17:18:36.616582
2025-02-21 17:18:36,618 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status
2025-02-21 17:18:36,619 INFO    WriterThread:23009 [datastore.py:open_for_write():87] open: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/run-su28ogb5.wandb
2025-02-21 17:18:36,619 DEBUG   SenderThread:23009 [sender.py:send():391] send: header
2025-02-21 17:18:36,620 DEBUG   SenderThread:23009 [sender.py:send():391] send: run
2025-02-21 17:18:37,428 INFO    SenderThread:23009 [dir_watcher.py:__init__():211] watching files in: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files
2025-02-21 17:18:37,428 INFO    SenderThread:23009 [sender.py:_start_run_threads():1200] run started: su28ogb5 with start time 1740133116.616347
2025-02-21 17:18:37,434 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: run_start
2025-02-21 17:18:37,442 DEBUG   HandlerThread:23009 [system_info.py:__init__():26] System info init
2025-02-21 17:18:37,442 DEBUG   HandlerThread:23009 [system_info.py:__init__():41] System info init done
2025-02-21 17:18:37,442 INFO    HandlerThread:23009 [system_monitor.py:start():194] Starting system monitor
2025-02-21 17:18:37,442 INFO    SystemMonitor:23009 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-02-21 17:18:37,442 INFO    HandlerThread:23009 [system_monitor.py:probe():214] Collecting system info
2025-02-21 17:18:37,442 INFO    SystemMonitor:23009 [interfaces.py:start():188] Started cpu monitoring
2025-02-21 17:18:37,443 INFO    SystemMonitor:23009 [interfaces.py:start():188] Started disk monitoring
2025-02-21 17:18:37,443 INFO    SystemMonitor:23009 [interfaces.py:start():188] Started gpu monitoring
2025-02-21 17:18:37,444 INFO    SystemMonitor:23009 [interfaces.py:start():188] Started memory monitoring
2025-02-21 17:18:37,444 INFO    SystemMonitor:23009 [interfaces.py:start():188] Started network monitoring
2025-02-21 17:18:37,450 DEBUG   HandlerThread:23009 [system_info.py:probe():152] Probing system
2025-02-21 17:18:37,452 DEBUG   HandlerThread:23009 [system_info.py:_probe_git():137] Probing git
2025-02-21 17:18:37,454 DEBUG   HandlerThread:23009 [system_info.py:_probe_git():145] Probing git done
2025-02-21 17:18:37,454 DEBUG   HandlerThread:23009 [system_info.py:probe():200] Probing system done
2025-02-21 17:18:37,454 DEBUG   HandlerThread:23009 [system_monitor.py:probe():223] {'os': 'Linux-6.8.0-52-generic-x86_64-with-glibc2.39', 'python': '3.12.7', 'heartbeatAt': '2025-02-21T10:18:37.450790', 'startedAt': '2025-02-21T10:18:36.613280', 'docker': None, 'cuda': None, 'args': ('--app', '.', '--num-supernodes', '100', '--backend-config', '{"client-resources": {"num-cpus": 4, "num-gpus": 0.25}}'), 'state': 'running', 'program': '/home/khanhtl/miniconda3/envs/FL/bin/flower-simulation', 'codePathLocal': None, 'git': {'remote': None, 'commit': None}, 'email': '128336094+khanh22010449@users.noreply.github.com', 'root': '/home/khanhtl/Code/FL', 'host': 'khanhtl', 'username': 'khanhtl', 'executable': '/home/khanhtl/miniconda3/envs/FL/bin/python3.12', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2979.3467499999997, 'min': 400.0, 'max': 4785.0}, 'cpu_freq_per_core': [{'current': 4492.662, 'min': 400.0, 'max': 4785.0}, {'current': 4508.791, 'min': 400.0, 'max': 4785.0}, {'current': 3008.567, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}, {'current': 2991.698, 'min': 400.0, 'max': 4785.0}, {'current': 3010.443, 'min': 400.0, 'max': 4785.0}, {'current': 2994.038, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}, {'current': 2993.577, 'min': 400.0, 'max': 4785.0}, {'current': 2994.225, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}, {'current': 4488.881, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}, {'current': 2992.784, 'min': 400.0, 'max': 4785.0}, {'current': 400.0, 'min': 400.0, 'max': 4785.0}], 'disk': {'/': {'total': 182.2811393737793, 'used': 130.24899291992188}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 22.767772674560547}}
2025-02-21 17:18:37,454 INFO    HandlerThread:23009 [system_monitor.py:probe():224] Finished collecting system info
2025-02-21 17:18:37,454 INFO    HandlerThread:23009 [system_monitor.py:probe():227] Publishing system info
2025-02-21 17:18:37,454 DEBUG   HandlerThread:23009 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-02-21 17:18:38,429 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/conda-environment.yaml
2025-02-21 17:18:39,429 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/conda-environment.yaml
2025-02-21 17:18:39,571 DEBUG   HandlerThread:23009 [system_info.py:_save_conda():224] Saving conda packages done
2025-02-21 17:18:39,572 INFO    HandlerThread:23009 [system_monitor.py:probe():229] Finished publishing system info
2025-02-21 17:18:39,573 DEBUG   SenderThread:23009 [sender.py:send():391] send: files
2025-02-21 17:18:39,573 INFO    SenderThread:23009 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2025-02-21 17:18:39,638 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: python_packages
2025-02-21 17:18:39,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: python_packages
2025-02-21 17:18:39,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:18:39,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:18:39,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:18:39,974 DEBUG   SenderThread:23009 [sender.py:send():391] send: telemetry
2025-02-21 17:18:40,429 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:18:40,430 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/requirements.txt
2025-02-21 17:18:40,430 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/wandb-metadata.json
2025-02-21 17:18:40,555 INFO    wandb-upload_0:23009 [upload_job.py:push():130] Uploaded file /tmp/tmpqpj_0sg6wandb/1gds0f43-wandb-metadata.json
2025-02-21 17:18:41,976 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:18:42,430 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:18:44,943 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: partial_history
2025-02-21 17:18:44,943 DEBUG   SenderThread:23009 [sender.py:send():391] send: telemetry
2025-02-21 17:18:46,431 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:18:47,432 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:18:47,944 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:18:49,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:18:53,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:18:54,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:18:54,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:18:59,077 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:18:59,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:02,435 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:19:04,280 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:04,436 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:19:08,437 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/output.log
2025-02-21 17:19:09,573 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:09,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:19:09,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:09,895 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:19:10,437 INFO    Thread-12 :23009 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_TEXT/wandb/run-20250221_171836-su28ogb5/files/config.yaml
2025-02-21 17:19:15,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:19,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:20,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:24,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:19:24,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:19:25,987 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:29,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:31,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:36,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:37,445 DEBUG   SystemMonitor:23009 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-02-21 17:19:37,445 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:19:39,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:19:39,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:19:39,680 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:44,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: keepalive
2025-02-21 17:19:46,430 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:49,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:19:51,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:54,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:19:54,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:19:56,898 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:19:59,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:02,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:07,446 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:20:08,446 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:09,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:20:09,639 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:20:09,679 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:13,999 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:19,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:19,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:24,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:20:24,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:20:25,007 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:29,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:30,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:35,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:37,447 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:20:39,639 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:20:39,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:20:39,681 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:40,988 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:46,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:49,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:20:52,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:54,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:20:54,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:20:59,141 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:20:59,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:04,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:07,447 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:21:09,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:21:09,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:21:09,681 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:10,164 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:15,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:19,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:21,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:24,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:21:24,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:21:26,936 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:29,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:32,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:37,448 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:21:38,449 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:39,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:21:39,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:21:39,681 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:43,938 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:49,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:21:49,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:54,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:21:54,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:21:56,561 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:21:59,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:01,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:22:06,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:22:07,448 DEBUG   SenderThread:23009 [sender.py:send():391] send: stats
2025-02-21 17:22:09,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:22:09,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:22:09,680 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:12,450 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:22:17,644 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:22:19,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:23,644 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: status_report
2025-02-21 17:22:24,640 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: stop_status
2025-02-21 17:22:24,640 DEBUG   SenderThread:23009 [sender.py:send_request():418] send_request: stop_status
2025-02-21 17:22:29,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:34,644 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: keepalive
2025-02-21 17:22:39,641 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:44,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: keepalive
2025-02-21 17:22:48,309 INFO    SenderThread:23009 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x713dcb70a030>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x713dcb70a030>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x713dcb70a030>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))
2025-02-21 17:22:49,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:22:54,643 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: keepalive
2025-02-21 17:22:59,642 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: internal_messages
2025-02-21 17:23:04,644 DEBUG   HandlerThread:23009 [handler.py:handle_request():158] handle_request: keepalive
2025-02-21 17:23:07,500 INFO    memory    :23009 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2025-02-21 17:23:07,501 DEBUG   SystemMonitor:23009 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-02-21 17:23:07,501 DEBUG   SystemMonitor:23009 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-02-21 17:23:08,474 INFO    MainThread:23009 [internal.py:handle_exit():75] Internal process exited
